# Config file for pipeline_fl_rna.py

## general options

# Copyright statement
copyright: cribbslab (2021)

FP: AAGCAGTGGTATCAACGCAGAGTGAAT
RP: GTACTCTGCGTTGATACCACTGCTT

## edit distance for primer matching
error: 0.3
split: 4000000


## usually 4hrs is enough - if pipeline fails try 8 or 12hrs
job_options: -t 04:00:00

## usually 20G sufficient, occassionally needs 40G.
splitter_mem: 20G
