# Config file for pipeline_split_by_index.py

## general options

# Copyright statement
copyright: cribbslab (2021)

FP: AAGCAGTGGTATCAACGCAGAGT

indexes:
  - AAATTTGGGCCC
  - TTTCCCAAAGGG
  - GGGAAACCCTTT
  - CCCGGGTTTAAA
  - AAACCCGGGAAA
  - TTTGGGAAATTT
  - GGGTTTCCCGGG
  - CCCAAATTTCCC
  - AAAGGGAAAGGG
  - TTTAAATTTAAA
  - GGGCCCGGGCCC
  - CCCTTTCCCTTT

#change error depending on number of barcodes - 3 or 4 is best for this set
error: 4
split: 4000000

job_options: -t 18:00:00

